### ISSUE TITLE
Alternative to WhoisXMLAPI

### ISSUE THREAD

**Issue by ip2location-com** [RH-ISAC/PyOTI#11]
It would be good to have an alternative WHOIS information provider [IP2Location.io](https://www.ip2location.io/) instead of just relying on WhoisXMLAPI. Perhaps you can consider the use of the [Domain WHOIS lookup](https://www.ip2location.io/ip2whois-documentation) in the IP2Location.io API. If you sign up for a free API plan and use its API key, you can get 500 Domain WHOIS queries per month.

**Comment by goodlandsecurity** [comment]
sorry that i missed this for quite a while, my apologies. however, please take a look at the addition in the most recent commit: 1fcc142b7ceef08b7b4096859efede99ed8dc7bc

**Comment by ip2location-com** [comment]
Hi @goodlandsecurity,

Sorry for missing this reply. The commit looks good to us, we believe you can proceed on your side.

**Comment by goodlandsecurity** [comment]
Thanks for the input!
